package i18n

var localeZH = map[string]string{
	"app.subtitle":    "FTP • FTPS • SFTP  ·  快速主机管理  ·  GhostFTP",
	"badge.connected": "● 已连接", "badge.disconnected": "● 未连接", "profile.quick": "快速连接（无配置）", "profile.save": "保存配置", "profile.delete": "删除配置",
	"common.settings": "设置", "common.about": "关于", "common.connect": "连接", "common.disconnect": "断开", "common.up": "上一级", "common.folder": "文件夹…", "common.refresh": "刷新", "common.new_folder": "新建文件夹", "common.rename": "重命名", "common.delete": "删除", "common.permissions": "权限", "common.cancel": "取消",
	"auth.private_key": "私钥…", "section.local": "本地计算机", "section.remote": "服务器", "section.transfers": "传输", "transfer.upload": "上传", "transfer.download": "下载", "transfer.pause": "暂停", "transfer.resume": "继续", "transfer.retry": "重试", "transfer.clear": "清除已完成",
	"status.ready": "就绪。请选择已保存的配置或输入服务器信息。", "status.refresh_all": "正在刷新本地和远程视图…",
	"cue.host": "FTP/SFTP 服务器，例如 ftp.example.cn", "cue.user": "用户名，例如 user@example.cn", "cue.password": "FTP / SFTP 密码", "cue.private_key": "SFTP 私钥（可选）", "cue.passphrase": "私钥口令", "cue.saved_password": "已保存密码 — 留空即可使用", "cue.saved_passphrase": "已保存私钥口令 — 留空即可使用",
	"column.name": "名称", "column.type": "类型", "column.size": "大小", "column.modified": "修改时间", "column.direction": "方向", "column.local": "本地", "column.remote": "服务器", "column.status": "状态", "column.progress": "进度", "type.file": "文件", "type.folder": "文件夹", "type.link": "链接", "direction.upload": "上传", "direction.download": "下载", "status.queued": "排队中", "status.running": "进行中", "status.done": "已完成", "status.failed": "失败", "status.cancelled": "已取消", "status.skipped": "已跳过",
	"transfer.summary": "%d 个活动  •  %d 个排队  •  %d 个完成", "transfer.summary_skipped": "  •  %d 个跳过", "transfer.summary_failed": "  •  %d 个失败/取消",
	"settings.load_failed": "无法加载设置；正在使用安全默认值。", "settings.title": "GhostFTP — 设置", "settings.invalid_value": "无效值", "settings.enter_range": "请输入 %d 到 %d 之间的数字。", "settings.parallel": "并行传输数（1–8）：", "settings.timeout": "连接超时（5–60 秒）：", "settings.retries": "失败传输自动重试（0–3 次）：", "settings.retry_delay": "自动重试间隔（1–30 秒）：", "settings.backup_title": "覆盖前备份？", "settings.backup_body": "是 = 保留现有文件的备份。\n否 = 成功传输后删除临时安全备份。", "settings.skip_title": "跳过已存在的文件？", "settings.skip_body": "是 = 不覆盖已有目标文件。\n否 = GhostFTP 按备份设置安全替换。", "settings.confirm_delete_title": "删除前确认？", "settings.confirm_delete_body": "建议对本地和远程文件保持启用。", "settings.save_failed": "设置未保存", "settings.save_failed_body": "当前无法保存设置。", "settings.retry_none": "不自动重试", "settings.retry_count": "自动重试：%d", "settings.overwrite": "已启用覆盖", "settings.skip_existing": "跳过已存在文件", "settings.saved": "设置已保存。并行传输：%d • 连接：%d 秒 • %s • %s",
	"about.title": "关于", "about.heading": "安全、简单的 FTP、FTPS 和 SFTP 文件传输。", "about.body": "GhostFTP 不跟踪用户，也不会把输入的数据发送给第三方。\n已保存的配置仅保留在此计算机上，并由 Windows 保护。\n\nGhostFTP\n%s\n%s",
	"connection.invalid_port": "无效端口", "connection.invalid_port_body": "端口必须是 1 到 65535 之间的数字。", "connection.invalid_data": "连接信息无效", "connection.invalid_data_body": "请检查服务器、端口和用户名。", "connection.connecting": "正在连接 %s…", "connection.failed": "连接失败", "connection.failed_status": "连接失败。请检查信息后重试。", "connection.failed_body": "请检查登录信息和网络连接。", "sftp.security": "GhostFTP — SFTP 安全", "sftp.new_key": "新的 SFTP 服务器密钥", "sftp.trust_body": "接受前请核对服务器密钥指纹：\n\n%s\n\n是否信任此服务器？", "sftp.cancelled": "SFTP 连接已取消。", "sftp.verifying": "正在验证 SFTP 密钥并连接…", "sftp.failed_status": "SFTP 连接失败。", "sftp.failed_body": "请检查登录信息和 SFTP 设置。", "connection.connected": "已连接：%s", "disconnect.title": "GhostFTP — 断开连接", "disconnect.question": "断开连接并取消活动传输？", "disconnect.body": "断开前会取消所有排队或正在进行的传输。", "disconnect.progress": "正在断开…", "disconnect.warning": "连接已关闭，但有警告。", "disconnect.done": "已断开。", "key.choose_failed": "无法选择私钥", "key.choose_failed_body": "当前无法选择私钥。", "profile.load_failed": "当前无法加载已保存的配置。",
	"error.session_closing": "上一个连接仍在安全关闭中。请稍后重试。", "error.disconnect_closing": "连接仍在安全关闭中。旧会话关闭后即可重新连接。", "error.cancelled": "连接或操作已取消。", "error.timeout": "服务器未及时响应。请检查地址、端口和网络连接后重试。", "error.hostkey_changed": "服务器安全密钥已更改。为保护您，连接已被阻止。", "error.sftp_unavailable": "SFTP 支持不可用。请启用 Windows 的 OpenSSH Client 功能。", "error.sftp_hostkey_missing": "SFTP 服务器未返回安全主机密钥。请检查地址、端口以及 SSH/SFTP 服务。", "error.auth": "登录被拒绝。请检查完整用户名和密码；共享主机的 FTP 用户名通常类似 user@example.cn。", "error.ftp_limit": "FTP 服务器暂不接受新会话，或已达到连接上限。请关闭其他 FTP 会话后重试。", "error.ftp_data": "FTP 数据连接无法建立或已中断。请检查防火墙/网络和被动 FTP 端口。", "error.resolve": "找不到服务器。请检查服务器地址。", "error.refused": "服务器拒绝了所选端口上的连接。请检查协议和端口。", "error.connection_lost": "与服务器的连接已中断。请重新连接并重试操作。", "error.tls": "无法验证安全连接。请检查证书和 FTPS 服务器设置。", "error.disk": "没有足够空间完成操作。", "error.permission": "您没有访问此文件或文件夹的权限。", "error.not_found": "文件或文件夹已不可用。请刷新视图后重试。", "error.exists": "已存在同名项目。", "error.not_connected": "您尚未连接服务器。", "error.queue_full": "传输队列已满。请清除已完成的传输后重试。", "error.structure_large": "所选结构过大，无法作为一次安全操作处理。", "error.invalid_port": "端口必须是 1 到 65535 之间的数字。", "error.invalid_host": "服务器地址无效。", "error.invalid_user": "用户名无效。", "error.invalid_name": "不允许使用此文件或文件夹名称。", "error.generic": "操作失败。请检查连接后重试。",
	"terminal.secret_hide_failed": "无法在终端中安全隐藏凭据输入", "terminal.protocol": "协议 (ftp/ftps/ftpsi/sftp)", "terminal.server": "服务器", "terminal.port": "端口", "terminal.username": "用户名", "terminal.private_key": "私钥", "terminal.key_passphrase": "私钥口令（无则按 Enter）", "terminal.password": "密码", "terminal.port_number": "端口必须是数字", "terminal.sftp_key_required": "Linux/macOS SFTP 需要明确指定私钥", "terminal.sftp_passphrase_unsupported": "Linux/macOS SFTP 当前仅支持无口令私钥", "terminal.fingerprint": "SFTP 主机密钥指纹：", "terminal.trust": "是否信任此服务器？(是/否)", "terminal.server_not_connected": "服务器未确认活动连接", "terminal.title": "GhostFTP %s — %s 终端客户端", "terminal.privacy": "无遥测 FTP/FTPS/SFTP 客户端。不会在终端输出秘密信息。", "terminal.connect_failed": "连接失败。请检查信息后重试。", "terminal.connected": "已连接：%s:%d", "terminal.commands": "命令：ls, cd, mkdir, rename, delete, chmod, get, put, pwd, language, help, quit", "terminal.quote_paths": "包含空格的路径和名称请使用单引号或双引号。", "terminal.invalid_command": "无效命令：%s", "terminal.unknown_command": "未知命令。请输入 'help'。", "terminal.transfer_done": "传输完成。", "terminal.transfer_skipped": "目标已存在，因此传输被跳过", "terminal.transfer_missing": "传输已不在队列中", "terminal.transfer_failed": "传输失败", "terminal.items": "%d 个项目", "terminal.item_file": "文件", "terminal.item_folder": "目录", "terminal.item_link": "链接", "terminal.language_usage": "用法：language <en|hr|de|fr|es|tr|el|pt|zh|ru|hi|ja>", "terminal.language_saved": "语言已切换为 %s。",
}

var localeRU = map[string]string{
	"app.subtitle":    "FTP • FTPS • SFTP  ·  Быстрое управление хостингом  ·  GhostFTP",
	"badge.connected": "● ПОДКЛЮЧЕНО", "badge.disconnected": "● ОТКЛЮЧЕНО", "profile.quick": "Быстрое подключение (без профиля)", "profile.save": "Сохранить профиль", "profile.delete": "Удалить профиль",
	"common.settings": "Настройки", "common.about": "О программе", "common.connect": "Подключить", "common.disconnect": "Отключить", "common.up": "Вверх", "common.folder": "Папка…", "common.refresh": "Обновить", "common.new_folder": "Новая папка", "common.rename": "Переименовать", "common.delete": "Удалить", "common.permissions": "Права", "common.cancel": "Отмена",
	"auth.private_key": "Закрытый ключ…", "section.local": "ЛОКАЛЬНЫЙ КОМПЬЮТЕР", "section.remote": "СЕРВЕР", "section.transfers": "ПЕРЕДАЧИ", "transfer.upload": "Загрузить", "transfer.download": "Скачать", "transfer.pause": "Пауза", "transfer.resume": "Продолжить", "transfer.retry": "Повторить", "transfer.clear": "Очистить завершённые",
	"status.ready": "Готово. Выберите сохранённый профиль или введите данные сервера.", "status.refresh_all": "Обновление локального и удалённого представления…",
	"cue.host": "FTP/SFTP-сервер, например ftp.example.ru", "cue.user": "Имя пользователя, возможно user@example.ru", "cue.password": "Пароль FTP / SFTP", "cue.private_key": "Закрытый ключ SFTP (необязательно)", "cue.passphrase": "Парольная фраза закрытого ключа", "cue.saved_password": "Пароль сохранён — оставьте пустым, чтобы использовать", "cue.saved_passphrase": "Парольная фраза сохранена — оставьте пустым, чтобы использовать",
	"column.name": "Имя", "column.type": "Тип", "column.size": "Размер", "column.modified": "Изменён", "column.direction": "Направление", "column.local": "Локально", "column.remote": "Сервер", "column.status": "Статус", "column.progress": "Прогресс", "type.file": "файл", "type.folder": "папка", "type.link": "ссылка", "direction.upload": "Загрузка", "direction.download": "Скачивание", "status.queued": "В очереди", "status.running": "Выполняется", "status.done": "Готово", "status.failed": "Ошибка", "status.cancelled": "Отменено", "status.skipped": "Пропущено",
	"transfer.summary": "%d активных  •  %d в очереди  •  %d завершено", "transfer.summary_skipped": "  •  %d пропущено", "transfer.summary_failed": "  •  %d ошибок/отменено",
	"settings.load_failed": "Не удалось загрузить настройки; используются безопасные значения по умолчанию.", "settings.title": "GhostFTP — Настройки", "settings.invalid_value": "Недопустимое значение", "settings.enter_range": "Введите число от %d до %d.", "settings.parallel": "Параллельные передачи (1–8):", "settings.timeout": "Тайм-аут подключения (5–60 секунд):", "settings.retries": "Автоматически повторять неудачную передачу (0–3 раза):", "settings.retry_delay": "Пауза между автоматическими попытками (1–30 секунд):", "settings.backup_title": "Создавать резервную копию перед перезаписью?", "settings.backup_body": "Да = сохранить копию существующего файла.\nНет = удалить временную защитную копию после успешной передачи.", "settings.skip_title": "Пропускать уже существующие файлы?", "settings.skip_body": "Да = существующие файлы назначения не будут перезаписаны.\nНет = GhostFTP безопасно заменит их согласно настройке резервного копирования.", "settings.confirm_delete_title": "Подтверждать удаление?", "settings.confirm_delete_body": "Рекомендуется оставить этот параметр включённым для локальных и удалённых файлов.", "settings.save_failed": "Настройки не сохранены", "settings.save_failed_body": "Сейчас невозможно сохранить настройки.", "settings.retry_none": "без автоматических повторов", "settings.retry_count": "автоматические повторы: %d", "settings.overwrite": "перезапись включена", "settings.skip_existing": "существующие файлы пропускаются", "settings.saved": "Настройки сохранены. Параллельные передачи: %d • подключение: %d с • %s • %s",
	"about.title": "О программе", "about.heading": "Безопасная и простая передача файлов по FTP, FTPS и SFTP.", "about.body": "GhostFTP не отслеживает пользователей и не отправляет введённые данные третьим лицам.\nСохранённые профили остаются на этом компьютере и защищаются Windows.\n\nGhostFTP\n%s\n%s",
	"connection.invalid_port": "Недопустимый порт", "connection.invalid_port_body": "Порт должен быть числом от 1 до 65535.", "connection.invalid_data": "Неверные данные подключения", "connection.invalid_data_body": "Проверьте сервер, порт и имя пользователя.", "connection.connecting": "Подключение к %s…", "connection.failed": "Не удалось подключиться", "connection.failed_status": "Подключение не удалось. Проверьте данные и повторите попытку.", "connection.failed_body": "Проверьте учётные данные и сетевое подключение.", "sftp.security": "GhostFTP — Безопасность SFTP", "sftp.new_key": "Новый ключ SFTP-сервера", "sftp.trust_body": "Проверьте отпечаток ключа сервера перед принятием:\n\n%s\n\nДоверять этому серверу?", "sftp.cancelled": "Подключение SFTP отменено.", "sftp.verifying": "Проверка ключа SFTP и подключение…", "sftp.failed_status": "Подключение SFTP не удалось.", "sftp.failed_body": "Проверьте учётные данные и настройки SFTP.", "connection.connected": "Подключено: %s", "disconnect.title": "GhostFTP — Отключение", "disconnect.question": "Отключиться и отменить активные передачи?", "disconnect.body": "Все передачи в очереди или в процессе будут отменены перед отключением.", "disconnect.progress": "Отключение…", "disconnect.warning": "Соединение закрыто с предупреждением.", "disconnect.done": "Отключено.", "key.choose_failed": "Не удалось выбрать закрытый ключ", "key.choose_failed_body": "Сейчас невозможно выбрать закрытый ключ.", "profile.load_failed": "Сейчас невозможно загрузить сохранённые профили.",
	"error.session_closing": "Предыдущее соединение всё ещё безопасно закрывается. Повторите попытку через несколько секунд.", "error.disconnect_closing": "Соединение всё ещё безопасно закрывается. Повторное подключение станет доступно после закрытия старого сеанса.", "error.cancelled": "Подключение или операция отменены.", "error.timeout": "Сервер не ответил вовремя. Проверьте адрес, порт и сеть и повторите попытку.", "error.hostkey_changed": "Ключ безопасности сервера изменился. Соединение заблокировано для вашей защиты.", "error.sftp_unavailable": "Поддержка SFTP недоступна. Включите компонент OpenSSH Client в Windows.", "error.sftp_hostkey_missing": "SFTP-сервер не вернул безопасный ключ хоста. Проверьте адрес, порт и службу SSH/SFTP.", "error.auth": "Вход отклонён. Проверьте полное имя пользователя и пароль; на shared hosting FTP-пользователь часто имеет вид user@example.ru.", "error.ftp_limit": "FTP-сервер не принимает новый сеанс или достигнут лимит подключений. Закройте другие FTP-сеансы и повторите попытку.", "error.ftp_data": "Не удалось открыть FTP-соединение данных или оно было прервано. Проверьте firewall/сеть и пассивные FTP-порты.", "error.resolve": "Сервер не найден. Проверьте адрес сервера.", "error.refused": "Сервер отклонил подключение на выбранном порту. Проверьте протокол и порт.", "error.connection_lost": "Соединение с сервером прервано. Подключитесь снова и повторите операцию.", "error.tls": "Не удалось подтвердить безопасное соединение. Проверьте сертификат и настройки FTPS.", "error.disk": "Недостаточно места для завершения операции.", "error.permission": "У вас нет прав на этот файл или папку.", "error.not_found": "Файл или папка больше недоступны. Обновите представление и повторите попытку.", "error.exists": "Элемент с таким именем уже существует.", "error.not_connected": "Вы не подключены к серверу.", "error.queue_full": "Очередь передач заполнена. Очистите завершённые передачи и повторите попытку.", "error.structure_large": "Выбранная структура слишком велика для одной безопасной операции.", "error.invalid_port": "Порт должен быть числом от 1 до 65535.", "error.invalid_host": "Адрес сервера недопустим.", "error.invalid_user": "Имя пользователя недопустимо.", "error.invalid_name": "Имя файла или папки не разрешено.", "error.generic": "Операция завершилась ошибкой. Проверьте соединение и повторите попытку.",
	"terminal.secret_hide_failed": "Невозможно безопасно скрыть ввод учётных данных в терминале", "terminal.protocol": "Протокол (ftp/ftps/ftpsi/sftp)", "terminal.server": "Сервер", "terminal.port": "Порт", "terminal.username": "Имя пользователя", "terminal.private_key": "Закрытый ключ", "terminal.key_passphrase": "Парольная фраза закрытого ключа (Enter, если нет)", "terminal.password": "Пароль", "terminal.port_number": "порт должен быть числом", "terminal.sftp_key_required": "SFTP в Linux/macOS требует явный закрытый ключ", "terminal.sftp_passphrase_unsupported": "SFTP в Linux/macOS сейчас поддерживает только закрытые ключи без парольной фразы", "terminal.fingerprint": "Отпечаток host-key SFTP:", "terminal.trust": "Доверять этому серверу? (да/нет)", "terminal.server_not_connected": "сервер не подтвердил активное соединение", "terminal.title": "GhostFTP %s — терминальный клиент %s", "terminal.privacy": "FTP/FTPS/SFTP-клиент без телеметрии. Секреты никогда не выводятся в терминал.", "terminal.connect_failed": "Подключение не удалось. Проверьте данные и повторите попытку.", "terminal.connected": "Подключено: %s:%d", "terminal.commands": "Команды: ls, cd, mkdir, rename, delete, chmod, get, put, pwd, language, help, quit", "terminal.quote_paths": "Пути и имена с пробелами заключайте в одинарные или двойные кавычки.", "terminal.invalid_command": "Недопустимая команда: %s", "terminal.unknown_command": "Неизвестная команда. Введите 'help'.", "terminal.transfer_done": "Передача завершена.", "terminal.transfer_skipped": "передача пропущена, потому что назначение уже существует", "terminal.transfer_missing": "передача больше недоступна в очереди", "terminal.transfer_failed": "передача завершилась ошибкой", "terminal.items": "%d элементов", "terminal.item_file": "файл", "terminal.item_folder": "папк", "terminal.item_link": "ссыл", "terminal.language_usage": "Использование: language <en|hr|de|fr|es|tr|el|pt|zh|ru|hi|ja>", "terminal.language_saved": "Язык изменён на %s.",
}
