package i18n

var localeHI = map[string]string{
	"app.subtitle":    "FTP • FTPS • SFTP  ·  तेज़ होस्टिंग प्रबंधन  ·  GhostFTP",
	"badge.connected": "● कनेक्टेड", "badge.disconnected": "● डिस्कनेक्टेड", "profile.quick": "त्वरित कनेक्ट (बिना प्रोफ़ाइल)", "profile.save": "प्रोफ़ाइल सहेजें", "profile.delete": "प्रोफ़ाइल हटाएँ",
	"common.settings": "सेटिंग्स", "common.about": "परिचय", "common.connect": "कनेक्ट", "common.disconnect": "डिस्कनेक्ट", "common.up": "ऊपर", "common.folder": "फ़ोल्डर…", "common.refresh": "रीफ़्रेश", "common.new_folder": "नया फ़ोल्डर", "common.rename": "नाम बदलें", "common.delete": "हटाएँ", "common.permissions": "अनुमतियाँ", "common.cancel": "रद्द करें",
	"auth.private_key": "निजी कुंजी…", "section.local": "स्थानीय कंप्यूटर", "section.remote": "सर्वर", "section.transfers": "ट्रांसफ़र", "transfer.upload": "अपलोड", "transfer.download": "डाउनलोड", "transfer.pause": "रोकें", "transfer.resume": "जारी रखें", "transfer.retry": "फिर प्रयास करें", "transfer.clear": "पूर्ण साफ़ करें",
	"status.ready": "तैयार। सहेजी गई प्रोफ़ाइल चुनें या सर्वर विवरण दर्ज करें।", "status.refresh_all": "स्थानीय और रिमोट दृश्य रीफ़्रेश किए जा रहे हैं…",
	"cue.host": "FTP/SFTP सर्वर, जैसे ftp.example.in", "cue.user": "उपयोगकर्ता नाम, user@example.in हो सकता है", "cue.password": "FTP / SFTP पासवर्ड", "cue.private_key": "SFTP निजी कुंजी (वैकल्पिक)", "cue.passphrase": "निजी कुंजी पासफ़्रेज़", "cue.saved_password": "सहेजा पासवर्ड — उपयोग के लिए खाली छोड़ें", "cue.saved_passphrase": "सहेजा कुंजी पासफ़्रेज़ — उपयोग के लिए खाली छोड़ें",
	"column.name": "नाम", "column.type": "प्रकार", "column.size": "आकार", "column.modified": "संशोधित", "column.direction": "दिशा", "column.local": "स्थानीय", "column.remote": "सर्वर", "column.status": "स्थिति", "column.progress": "प्रगति", "type.file": "फ़ाइल", "type.folder": "फ़ोल्डर", "type.link": "लिंक", "direction.upload": "अपलोड", "direction.download": "डाउनलोड", "status.queued": "कतार में", "status.running": "चल रहा", "status.done": "पूर्ण", "status.failed": "विफल", "status.cancelled": "रद्द", "status.skipped": "छोड़ा गया",
	"transfer.summary": "%d सक्रिय  •  %d कतार में  •  %d पूर्ण", "transfer.summary_skipped": "  •  %d छोड़े गए", "transfer.summary_failed": "  •  %d विफल/रद्द",
	"settings.load_failed": "सेटिंग्स लोड नहीं हुईं; सुरक्षित डिफ़ॉल्ट मान उपयोग किए जा रहे हैं।", "settings.title": "GhostFTP — सेटिंग्स", "settings.invalid_value": "अमान्य मान", "settings.enter_range": "%d से %d तक कोई संख्या दर्ज करें।", "settings.parallel": "समानांतर ट्रांसफ़र (1–8):", "settings.timeout": "कनेक्शन टाइमआउट (5–60 सेकंड):", "settings.retries": "विफल ट्रांसफ़र को स्वतः फिर प्रयास करें (0–3 बार):", "settings.retry_delay": "स्वचालित प्रयासों के बीच विराम (1–30 सेकंड):", "settings.backup_title": "ओवरराइट से पहले बैकअप?", "settings.backup_body": "हाँ = मौजूदा फ़ाइल की बैकअप प्रति रखें।\nनहीं = सफल ट्रांसफ़र के बाद अस्थायी सुरक्षा बैकअप हटाएँ।", "settings.skip_title": "पहले से मौजूद फ़ाइलें छोड़ें?", "settings.skip_body": "हाँ = मौजूदा लक्ष्य फ़ाइलें ओवरराइट नहीं होंगी।\nनहीं = GhostFTP बैकअप सेटिंग के अनुसार सुरक्षित रूप से बदलेगा।", "settings.confirm_delete_title": "हटाने से पहले पुष्टि?", "settings.confirm_delete_body": "स्थानीय और रिमोट फ़ाइलों के लिए इसे सक्षम रखना अनुशंसित है।", "settings.save_failed": "सेटिंग्स सहेजी नहीं गईं", "settings.save_failed_body": "सेटिंग्स अभी सहेजी नहीं जा सकतीं।", "settings.retry_none": "कोई स्वचालित पुनः प्रयास नहीं", "settings.retry_count": "स्वचालित पुनः प्रयास: %d", "settings.overwrite": "ओवरराइट सक्षम", "settings.skip_existing": "मौजूदा फ़ाइलें छोड़ी जाती हैं", "settings.saved": "सेटिंग्स सहेजी गईं। समानांतर ट्रांसफ़र: %d • कनेक्शन: %d सेकंड • %s • %s",
	"about.title": "परिचय", "about.heading": "FTP, FTPS और SFTP से सुरक्षित और सरल फ़ाइल ट्रांसफ़र।", "about.body": "GhostFTP उपयोगकर्ताओं को ट्रैक नहीं करता और दर्ज डेटा तीसरे पक्ष को नहीं भेजता।\nसहेजी गई प्रोफ़ाइल इसी कंप्यूटर पर रहती हैं और Windows द्वारा सुरक्षित होती हैं।\n\nGhostFTP\n%s\n%s",
	"connection.invalid_port": "अमान्य पोर्ट", "connection.invalid_port_body": "पोर्ट 1 से 65535 के बीच की संख्या होना चाहिए।", "connection.invalid_data": "अमान्य कनेक्शन विवरण", "connection.invalid_data_body": "सर्वर, पोर्ट और उपयोगकर्ता नाम जाँचें।", "connection.connecting": "%s से कनेक्ट किया जा रहा है…", "connection.failed": "कनेक्शन विफल", "connection.failed_status": "कनेक्शन विफल। विवरण जाँचें और फिर प्रयास करें।", "connection.failed_body": "लॉगिन विवरण और नेटवर्क कनेक्शन जाँचें।", "sftp.security": "GhostFTP — SFTP सुरक्षा", "sftp.new_key": "नया SFTP सर्वर कुंजी", "sftp.trust_body": "स्वीकार करने से पहले सर्वर कुंजी फ़िंगरप्रिंट सत्यापित करें:\n\n%s\n\nक्या आप इस सर्वर पर भरोसा करते हैं?", "sftp.cancelled": "SFTP कनेक्शन रद्द।", "sftp.verifying": "SFTP कुंजी सत्यापित कर कनेक्ट किया जा रहा है…", "sftp.failed_status": "SFTP कनेक्शन विफल।", "sftp.failed_body": "लॉगिन विवरण और SFTP सेटिंग्स जाँचें।", "connection.connected": "कनेक्टेड: %s", "disconnect.title": "GhostFTP — डिस्कनेक्ट", "disconnect.question": "डिस्कनेक्ट करें और सक्रिय ट्रांसफ़र रद्द करें?", "disconnect.body": "डिस्कनेक्ट करने से पहले कतार में या चल रहे सभी ट्रांसफ़र रद्द होंगे।", "disconnect.progress": "डिस्कनेक्ट किया जा रहा है…", "disconnect.warning": "कनेक्शन चेतावनी के साथ बंद हुआ।", "disconnect.done": "डिस्कनेक्टेड।", "key.choose_failed": "निजी कुंजी नहीं चुनी जा सकी", "key.choose_failed_body": "निजी कुंजी अभी नहीं चुनी जा सकती।", "profile.load_failed": "सहेजी गई प्रोफ़ाइल अभी लोड नहीं की जा सकतीं।",
	"error.session_closing": "पिछला कनेक्शन अभी सुरक्षित रूप से बंद हो रहा है। कुछ क्षण बाद फिर प्रयास करें।", "error.disconnect_closing": "कनेक्शन अभी सुरक्षित रूप से बंद हो रहा है। पुराना सत्र बंद होने पर पुनः कनेक्ट उपलब्ध होगा।", "error.cancelled": "कनेक्शन या ऑपरेशन रद्द किया गया।", "error.timeout": "सर्वर ने समय पर उत्तर नहीं दिया। पता, पोर्ट और नेटवर्क जाँचकर फिर प्रयास करें।", "error.hostkey_changed": "सर्वर की सुरक्षा कुंजी बदल गई है। आपकी सुरक्षा के लिए कनेक्शन रोक दिया गया।", "error.sftp_unavailable": "SFTP समर्थन उपलब्ध नहीं है। Windows में OpenSSH Client सुविधा सक्षम करें।", "error.sftp_hostkey_missing": "SFTP सर्वर ने सुरक्षा host key नहीं लौटाई। पता, पोर्ट और SSH/SFTP सेवा जाँचें।", "error.auth": "लॉगिन अस्वीकार हुआ। पूरा उपयोगकर्ता नाम और पासवर्ड जाँचें; shared hosting में FTP उपयोगकर्ता अक्सर user@example.in जैसा होता है।", "error.ftp_limit": "FTP सर्वर नया सत्र स्वीकार नहीं कर रहा या कनेक्शन सीमा पूरी हो गई। अन्य FTP सत्र बंद कर फिर प्रयास करें।", "error.ftp_data": "FTP डेटा कनेक्शन नहीं खुल सका या टूट गया। फ़ायरवॉल/नेटवर्क और passive FTP पोर्ट जाँचें।", "error.resolve": "सर्वर नहीं मिला। सर्वर पता जाँचें।", "error.refused": "सर्वर ने चुने गए पोर्ट पर कनेक्शन अस्वीकार किया। प्रोटोकॉल और पोर्ट जाँचें।", "error.connection_lost": "सर्वर कनेक्शन टूट गया। फिर कनेक्ट करें और ऑपरेशन दोहराएँ।", "error.tls": "सुरक्षित कनेक्शन सत्यापित नहीं हो सका। प्रमाणपत्र और FTPS सेटिंग्स जाँचें।", "error.disk": "ऑपरेशन पूरा करने के लिए पर्याप्त स्थान नहीं है।", "error.permission": "इस फ़ाइल या फ़ोल्डर के लिए आपके पास अनुमति नहीं है।", "error.not_found": "फ़ाइल या फ़ोल्डर अब उपलब्ध नहीं है। दृश्य रीफ़्रेश कर फिर प्रयास करें।", "error.exists": "इस नाम का आइटम पहले से मौजूद है।", "error.not_connected": "आप सर्वर से कनेक्ट नहीं हैं।", "error.queue_full": "ट्रांसफ़र कतार भरी हुई है। पूर्ण ट्रांसफ़र साफ़ कर फिर प्रयास करें।", "error.structure_large": "चुनी गई संरचना एक सुरक्षित ऑपरेशन के लिए बहुत बड़ी है।", "error.invalid_port": "पोर्ट 1 से 65535 के बीच की संख्या होना चाहिए।", "error.invalid_host": "सर्वर पता अमान्य है।", "error.invalid_user": "उपयोगकर्ता नाम अमान्य है।", "error.invalid_name": "फ़ाइल या फ़ोल्डर नाम अनुमत नहीं है।", "error.generic": "ऑपरेशन विफल। कनेक्शन जाँचें और फिर प्रयास करें।",
	"terminal.secret_hide_failed": "टर्मिनल में क्रेडेंशियल इनपुट सुरक्षित रूप से छिपाया नहीं जा सकता", "terminal.protocol": "प्रोटोकॉल (ftp/ftps/ftpsi/sftp)", "terminal.server": "सर्वर", "terminal.port": "पोर्ट", "terminal.username": "उपयोगकर्ता नाम", "terminal.private_key": "निजी कुंजी", "terminal.key_passphrase": "निजी कुंजी पासफ़्रेज़ (न हो तो Enter)", "terminal.password": "पासवर्ड", "terminal.port_number": "पोर्ट एक संख्या होना चाहिए", "terminal.sftp_key_required": "Linux/macOS SFTP को स्पष्ट निजी कुंजी चाहिए", "terminal.sftp_passphrase_unsupported": "Linux/macOS SFTP अभी केवल बिना पासफ़्रेज़ वाली निजी कुंजियों का समर्थन करता है", "terminal.fingerprint": "SFTP host-key फ़िंगरप्रिंट:", "terminal.trust": "क्या आप इस सर्वर पर भरोसा करते हैं? (हाँ/नहीं)", "terminal.server_not_connected": "सर्वर ने सक्रिय कनेक्शन की पुष्टि नहीं की", "terminal.title": "GhostFTP %s — %s टर्मिनल क्लाइंट", "terminal.privacy": "टेलीमेट्री-रहित FTP/FTPS/SFTP क्लाइंट। गुप्त जानकारी टर्मिनल में नहीं दिखाई जाती।", "terminal.connect_failed": "कनेक्शन विफल। विवरण जाँचें और फिर प्रयास करें।", "terminal.connected": "कनेक्टेड: %s:%d", "terminal.commands": "कमांड: ls, cd, mkdir, rename, delete, chmod, get, put, pwd, language, help, quit", "terminal.quote_paths": "स्पेस वाले पथ और नाम सिंगल या डबल कोट में रखें।", "terminal.invalid_command": "अमान्य कमांड: %s", "terminal.unknown_command": "अज्ञात कमांड। 'help' लिखें।", "terminal.transfer_done": "ट्रांसफ़र पूर्ण।", "terminal.transfer_skipped": "लक्ष्य पहले से मौजूद होने के कारण ट्रांसफ़र छोड़ा गया", "terminal.transfer_missing": "ट्रांसफ़र अब कतार में उपलब्ध नहीं है", "terminal.transfer_failed": "ट्रांसफ़र विफल", "terminal.items": "%d आइटम", "terminal.item_file": "फ़ाइल", "terminal.item_folder": "फ़ोल्ड", "terminal.item_link": "लिंक", "terminal.language_usage": "उपयोग: language <en|hr|de|fr|es|tr|el|pt|zh|ru|hi|ja>", "terminal.language_saved": "भाषा %s में बदल दी गई।",
}

var localeJA = map[string]string{
	"app.subtitle":    "FTP • FTPS • SFTP  ·  高速ホスティング管理  ·  GhostFTP",
	"badge.connected": "● 接続済み", "badge.disconnected": "● 未接続", "profile.quick": "クイック接続（プロファイルなし）", "profile.save": "プロファイル保存", "profile.delete": "プロファイル削除",
	"common.settings": "設定", "common.about": "このアプリについて", "common.connect": "接続", "common.disconnect": "切断", "common.up": "上へ", "common.folder": "フォルダー…", "common.refresh": "更新", "common.new_folder": "新しいフォルダー", "common.rename": "名前変更", "common.delete": "削除", "common.permissions": "権限", "common.cancel": "キャンセル",
	"auth.private_key": "秘密鍵…", "section.local": "ローカル コンピューター", "section.remote": "サーバー", "section.transfers": "転送", "transfer.upload": "アップロード", "transfer.download": "ダウンロード", "transfer.pause": "一時停止", "transfer.resume": "再開", "transfer.retry": "再試行", "transfer.clear": "完了済みを消去",
	"status.ready": "準備完了。保存済みプロファイルを選択するか、サーバー情報を入力してください。", "status.refresh_all": "ローカルとリモートの表示を更新しています…",
	"cue.host": "FTP/SFTP サーバー（例: ftp.example.jp）", "cue.user": "ユーザー名（user@example.jp 形式の場合があります）", "cue.password": "FTP / SFTP パスワード", "cue.private_key": "SFTP 秘密鍵（任意）", "cue.passphrase": "秘密鍵パスフレーズ", "cue.saved_password": "保存済みパスワード — 使用する場合は空欄", "cue.saved_passphrase": "保存済み鍵パスフレーズ — 使用する場合は空欄",
	"column.name": "名前", "column.type": "種類", "column.size": "サイズ", "column.modified": "更新日時", "column.direction": "方向", "column.local": "ローカル", "column.remote": "サーバー", "column.status": "状態", "column.progress": "進行状況", "type.file": "ファイル", "type.folder": "フォルダー", "type.link": "リンク", "direction.upload": "アップロード", "direction.download": "ダウンロード", "status.queued": "待機中", "status.running": "実行中", "status.done": "完了", "status.failed": "失敗", "status.cancelled": "キャンセル", "status.skipped": "スキップ",
	"transfer.summary": "%d 件実行中  •  %d 件待機中  •  %d 件完了", "transfer.summary_skipped": "  •  %d 件スキップ", "transfer.summary_failed": "  •  %d 件失敗/キャンセル",
	"settings.load_failed": "設定を読み込めませんでした。安全な既定値を使用します。", "settings.title": "GhostFTP — 設定", "settings.invalid_value": "無効な値", "settings.enter_range": "%d から %d の数値を入力してください。", "settings.parallel": "並列転送数（1–8）:", "settings.timeout": "接続タイムアウト（5–60 秒）:", "settings.retries": "失敗した転送を自動再試行（0–3 回）:", "settings.retry_delay": "自動再試行の間隔（1–30 秒）:", "settings.backup_title": "上書き前にバックアップしますか？", "settings.backup_body": "はい = 既存ファイルのバックアップを保持します。\nいいえ = 転送成功後に一時バックアップを削除します。", "settings.skip_title": "既存ファイルをスキップしますか？", "settings.skip_body": "はい = 既存の宛先ファイルを上書きしません。\nいいえ = バックアップ設定に従って GhostFTP が安全に置き換えます。", "settings.confirm_delete_title": "削除前に確認しますか？", "settings.confirm_delete_body": "ローカルとリモートのファイルでは有効のままにすることを推奨します。", "settings.save_failed": "設定を保存できませんでした", "settings.save_failed_body": "現在、設定を保存できません。", "settings.retry_none": "自動再試行なし", "settings.retry_count": "自動再試行: %d", "settings.overwrite": "上書き有効", "settings.skip_existing": "既存ファイルをスキップ", "settings.saved": "設定を保存しました。並列転送: %d • 接続: %d 秒 • %s • %s",
	"about.title": "このアプリについて", "about.heading": "FTP、FTPS、SFTP による安全で簡単なファイル転送。", "about.body": "GhostFTP はユーザーを追跡せず、入力したデータを第三者へ送信しません。\n保存済みプロファイルはこのコンピューター内に保持され、Windows によって保護されます。\n\nGhostFTP\n%s\n%s",
	"connection.invalid_port": "無効なポート", "connection.invalid_port_body": "ポートは 1 から 65535 の数値である必要があります。", "connection.invalid_data": "接続情報が無効です", "connection.invalid_data_body": "サーバー、ポート、ユーザー名を確認してください。", "connection.connecting": "%s に接続しています…", "connection.failed": "接続に失敗しました", "connection.failed_status": "接続に失敗しました。情報を確認して再試行してください。", "connection.failed_body": "ログイン情報とネットワーク接続を確認してください。", "sftp.security": "GhostFTP — SFTP セキュリティ", "sftp.new_key": "新しい SFTP サーバー鍵", "sftp.trust_body": "受け入れる前にサーバー鍵のフィンガープリントを確認してください:\n\n%s\n\nこのサーバーを信頼しますか？", "sftp.cancelled": "SFTP 接続をキャンセルしました。", "sftp.verifying": "SFTP 鍵を確認して接続しています…", "sftp.failed_status": "SFTP 接続に失敗しました。", "sftp.failed_body": "ログイン情報と SFTP 設定を確認してください。", "connection.connected": "接続済み: %s", "disconnect.title": "GhostFTP — 切断", "disconnect.question": "切断して実行中の転送をキャンセルしますか？", "disconnect.body": "切断前に、待機中または実行中のすべての転送がキャンセルされます。", "disconnect.progress": "切断しています…", "disconnect.warning": "警告を伴って接続を閉じました。", "disconnect.done": "切断しました。", "key.choose_failed": "秘密鍵を選択できませんでした", "key.choose_failed_body": "現在、秘密鍵を選択できません。", "profile.load_failed": "現在、保存済みプロファイルを読み込めません。",
	"error.session_closing": "前の接続を安全に終了しています。少し待ってから再試行してください。", "error.disconnect_closing": "接続を安全に終了しています。古いセッションが閉じると再接続できます。", "error.cancelled": "接続または操作がキャンセルされました。", "error.timeout": "サーバーが時間内に応答しませんでした。アドレス、ポート、ネットワークを確認して再試行してください。", "error.hostkey_changed": "サーバーのセキュリティ鍵が変更されました。保護のため接続をブロックしました。", "error.sftp_unavailable": "SFTP サポートを利用できません。Windows の OpenSSH Client 機能を有効にしてください。", "error.sftp_hostkey_missing": "SFTP サーバーが安全なホスト鍵を返しませんでした。アドレス、ポート、SSH/SFTP サービスを確認してください。", "error.auth": "ログインが拒否されました。完全なユーザー名とパスワードを確認してください。共有ホスティングでは FTP ユーザー名が user@example.jp の形式であることがあります。", "error.ftp_limit": "FTP サーバーが新しいセッションを受け付けていないか、接続上限に達しています。他の FTP セッションを閉じて再試行してください。", "error.ftp_data": "FTP データ接続を開けないか切断されました。ファイアウォール/ネットワークとパッシブ FTP ポートを確認してください。", "error.resolve": "サーバーが見つかりません。サーバーアドレスを確認してください。", "error.refused": "選択したポートでサーバーが接続を拒否しました。プロトコルとポートを確認してください。", "error.connection_lost": "サーバーとの接続が切断されました。再接続して操作を繰り返してください。", "error.tls": "安全な接続を確認できませんでした。証明書と FTPS 設定を確認してください。", "error.disk": "操作を完了するための空き容量が不足しています。", "error.permission": "このファイルまたはフォルダーへの権限がありません。", "error.not_found": "ファイルまたはフォルダーを利用できません。表示を更新して再試行してください。", "error.exists": "同じ名前の項目が既に存在します。", "error.not_connected": "サーバーに接続していません。", "error.queue_full": "転送キューがいっぱいです。完了済み転送を消去して再試行してください。", "error.structure_large": "選択した構造は、1 回の安全な操作には大きすぎます。", "error.invalid_port": "ポートは 1 から 65535 の数値である必要があります。", "error.invalid_host": "サーバーアドレスが無効です。", "error.invalid_user": "ユーザー名が無効です。", "error.invalid_name": "このファイル名またはフォルダー名は使用できません。", "error.generic": "操作に失敗しました。接続を確認して再試行してください。",
	"terminal.secret_hide_failed": "ターミナルで資格情報の入力を安全に非表示にできません", "terminal.protocol": "プロトコル (ftp/ftps/ftpsi/sftp)", "terminal.server": "サーバー", "terminal.port": "ポート", "terminal.username": "ユーザー名", "terminal.private_key": "秘密鍵", "terminal.key_passphrase": "秘密鍵パスフレーズ（ない場合は Enter）", "terminal.password": "パスワード", "terminal.port_number": "ポートは数値である必要があります", "terminal.sftp_key_required": "Linux/macOS の SFTP では明示的な秘密鍵が必要です", "terminal.sftp_passphrase_unsupported": "Linux/macOS の SFTP は現在、パスフレーズなしの秘密鍵のみをサポートしています", "terminal.fingerprint": "SFTP ホスト鍵フィンガープリント:", "terminal.trust": "このサーバーを信頼しますか？ (はい/いいえ)", "terminal.server_not_connected": "サーバーが有効な接続を確認しませんでした", "terminal.title": "GhostFTP %s — %s ターミナルクライアント", "terminal.privacy": "テレメトリなしの FTP/FTPS/SFTP クライアント。秘密情報をターミナルに表示しません。", "terminal.connect_failed": "接続に失敗しました。情報を確認して再試行してください。", "terminal.connected": "接続済み: %s:%d", "terminal.commands": "コマンド: ls, cd, mkdir, rename, delete, chmod, get, put, pwd, language, help, quit", "terminal.quote_paths": "空白を含むパスや名前はシングルクォートまたはダブルクォートで囲んでください。", "terminal.invalid_command": "無効なコマンド: %s", "terminal.unknown_command": "不明なコマンドです。'help' と入力してください。", "terminal.transfer_done": "転送が完了しました。", "terminal.transfer_skipped": "宛先が既に存在するため転送をスキップしました", "terminal.transfer_missing": "転送はキューに存在しません", "terminal.transfer_failed": "転送に失敗しました", "terminal.items": "%d 項目", "terminal.item_file": "ファイル", "terminal.item_folder": "フォルダ", "terminal.item_link": "リンク", "terminal.language_usage": "使用法: language <en|hr|de|fr|es|tr|el|pt|zh|ru|hi|ja>", "terminal.language_saved": "言語を %s に変更しました。",
}
