//go:build windows

package desktop

import "unsafe"

const (
	// LVN_KEYDOWN = LVN_FIRST - 55. Keeping it beside the behavior avoids
	// turning the generic Win32 definition file into a shortcut registry.
	lvnKeyDown = 0xFFFFFF65

	fshiftKeyboard = 0x04

	// Keep accelerator-only commands away from the control/menu ID ranges.
	idFocusLocalPath  = 7601
	idFocusRemotePath = 7602

	emSetSelKeyboard = 0x00B1

	// WM_COMMAND generated by TranslateAccelerator uses HIWORD(wParam)=1.
	// Button clicks use BN_CLICKED=0, so both paths must be recognized.
	acceleratorCommandNotification = 1
)

var setFocusKeyboard = user32.NewProc("SetFocus")

type nmLVKeyDown struct {
	Hdr   nmhdr
	VKey  uint16
	_     uint16
	Flags uint32
}

func nmLVKeyDownFromLParam(p uintptr) nmLVKeyDown {
	var n nmLVKeyDown
	if p != 0 {
		rtlMoveMemory.Call(uintptr(unsafe.Pointer(&n)), p, unsafe.Sizeof(n))
	}
	return n
}

func focusAndSelectEdit(hwnd uintptr) {
	if hwnd == 0 {
		return
	}
	setFocusKeyboard.Call(hwnd)
	sendMessageW.Call(hwnd, emSetSelKeyboard, 0, ^uintptr(0))
}

func (a *app) handleFileListKey(list uintptr, vKey uint16) bool {
	if a == nil || (list != a.localList && list != a.remoteList) {
		return false
	}
	action := filePaneKeyActionFor(vKey, len(selectedIndices(list)))
	if action == filePaneKeyNone {
		return false
	}

	local := list == a.localList
	switch action {
	case filePaneKeyOpen:
		if local {
			a.openSelectedLocal()
		} else {
			a.openSelectedRemote()
		}
	case filePaneKeyRename:
		if local {
			a.localRenameAction()
		} else {
			a.remoteRenameAction()
		}
	case filePaneKeyDelete:
		if local {
			a.localDeleteAction()
		} else {
			a.remoteDeleteAction()
		}
	case filePaneKeyUp:
		if local {
			a.command(idLocalUp)
		} else {
			a.command(idRemoteUp)
		}
	default:
		return false
	}
	return true
}
