package desktop

import "github.com/bren-wp/Host-FTP/internal/i18n"

type remoteEditWordsSet struct {
	Edit              string
	Title             string
	Save              string
	Reload            string
	Close             string
	Hint              string
	Opening           string
	Loaded            string
	Saving            string
	Saved             string
	Reloading         string
	Reloaded          string
	Conflict          string
	Unsupported       string
	DiscardClose      string
	DiscardReload     string
	MixedNewlines     string
	ConnectionChanged string
}

func remoteEditWords(language string) remoteEditWordsSet {
	language = i18n.Normalize(language)
	words := map[string]remoteEditWordsSet{
		"en": {
			Edit:              "Edit",
			Title:             "Remote editor",
			Save:              "Save",
			Reload:            "Reload",
			Close:             "Close",
			Hint:              "Ctrl+S save · Ctrl+R reload · Esc close",
			Opening:           "Opening remote file…",
			Loaded:            "Remote file opened.",
			Saving:            "Saving and verifying remote file…",
			Saved:             "Saved and verified.",
			Reloading:         "Reloading from server…",
			Reloaded:          "Reloaded from server.",
			Conflict:          "The server file changed after it was opened. Your edits were kept; reload before saving again.",
			Unsupported:       "Select one regular text file up to 4 MiB. Folders, links, binary files and larger files are not edited in place.",
			DiscardClose:      "Unsaved changes are still in the editor. Click Close again to discard them.",
			DiscardReload:     "Reload will discard unsaved changes. Click Reload again to continue.",
			MixedNewlines:     "This file uses mixed line endings. Ghost FTP will not edit it because that could change unrelated lines.",
			ConnectionChanged: "The server connection changed while the editor was open. Reopen the file before saving.",
		},
		"hr": {
			Edit:              "Uredi",
			Title:             "Udaljeni uređivač",
			Save:              "Spremi",
			Reload:            "Ponovno učitaj",
			Close:             "Zatvori",
			Hint:              "Ctrl+S spremi · Ctrl+R ponovno učitaj · Esc zatvori",
			Opening:           "Otvaranje udaljene datoteke…",
			Loaded:            "Udaljena datoteka je otvorena.",
			Saving:            "Spremanje i provjera udaljene datoteke…",
			Saved:             "Spremljeno i provjereno.",
			Reloading:         "Ponovno učitavanje s poslužitelja…",
			Reloaded:          "Ponovno učitano s poslužitelja.",
			Conflict:          "Datoteka na poslužitelju promijenjena je nakon otvaranja. Vaše izmjene su zadržane; ponovno učitajte datoteku prije novog spremanja.",
			Unsupported:       "Odaberite jednu običnu tekstualnu datoteku do 4 MiB. Mape, poveznice, binarne i veće datoteke ne uređuju se izravno.",
			DiscardClose:      "U uređivaču postoje nespremljene izmjene. Ponovno kliknite Zatvori da biste ih odbacili.",
			DiscardReload:     "Ponovno učitavanje odbacit će nespremljene izmjene. Ponovno kliknite Ponovno učitaj za nastavak.",
			MixedNewlines:     "Datoteka koristi miješane završetke redaka. Ghost FTP je neće uređivati jer bi to moglo promijeniti druge retke.",
			ConnectionChanged: "Veza s poslužiteljem promijenila se dok je uređivač bio otvoren. Ponovno otvorite datoteku prije spremanja.",
		},
		"de": {
			Edit:              "Bearbeiten",
			Title:             "Remote-Editor",
			Save:              "Speichern",
			Reload:            "Neu laden",
			Close:             "Schließen",
			Hint:              "Ctrl+S speichern · Ctrl+R neu laden · Esc schließen",
			Opening:           "Remote-Datei wird geöffnet…",
			Loaded:            "Remote-Datei geöffnet.",
			Saving:            "Remote-Datei wird gespeichert und geprüft…",
			Saved:             "Gespeichert und geprüft.",
			Reloading:         "Vom Server neu laden…",
			Reloaded:          "Vom Server neu geladen.",
			Conflict:          "Die Serverdatei wurde nach dem Öffnen geändert. Ihre Änderungen bleiben erhalten; laden Sie die Datei vor dem nächsten Speichern neu.",
			Unsupported:       "Wählen Sie eine normale Textdatei bis 4 MiB. Ordner, Links, Binärdateien und größere Dateien werden nicht direkt bearbeitet.",
			DiscardClose:      "Es gibt ungespeicherte Änderungen. Klicken Sie erneut auf Schließen, um sie zu verwerfen.",
			DiscardReload:     "Neu laden verwirft ungespeicherte Änderungen. Klicken Sie erneut auf Neu laden.",
			MixedNewlines:     "Diese Datei verwendet gemischte Zeilenenden. Ghost FTP bearbeitet sie nicht, um unbeabsichtigte Änderungen zu vermeiden.",
			ConnectionChanged: "Die Serververbindung hat sich geändert. Öffnen Sie die Datei vor dem Speichern erneut.",
		},
		"fr": {
			Edit:              "Modifier",
			Title:             "Éditeur distant",
			Save:              "Enregistrer",
			Reload:            "Recharger",
			Close:             "Fermer",
			Hint:              "Ctrl+S enregistrer · Ctrl+R recharger · Esc fermer",
			Opening:           "Ouverture du fichier distant…",
			Loaded:            "Fichier distant ouvert.",
			Saving:            "Enregistrement et vérification du fichier distant…",
			Saved:             "Enregistré et vérifié.",
			Reloading:         "Rechargement depuis le serveur…",
			Reloaded:          "Rechargé depuis le serveur.",
			Conflict:          "Le fichier du serveur a changé depuis son ouverture. Vos modifications sont conservées ; rechargez avant d'enregistrer à nouveau.",
			Unsupported:       "Sélectionnez un fichier texte normal de 4 Mio maximum. Les dossiers, liens, fichiers binaires et fichiers plus volumineux ne sont pas modifiés directement.",
			DiscardClose:      "Des modifications ne sont pas enregistrées. Cliquez de nouveau sur Fermer pour les abandonner.",
			DiscardReload:     "Recharger supprimera les modifications non enregistrées. Cliquez de nouveau sur Recharger.",
			MixedNewlines:     "Ce fichier utilise des fins de ligne mixtes. Ghost FTP refuse de le modifier pour éviter de changer d'autres lignes.",
			ConnectionChanged: "La connexion au serveur a changé. Rouvrez le fichier avant de l'enregistrer.",
		},
		"es": {
			Edit:              "Editar",
			Title:             "Editor remoto",
			Save:              "Guardar",
			Reload:            "Recargar",
			Close:             "Cerrar",
			Hint:              "Ctrl+S guardar · Ctrl+R recargar · Esc cerrar",
			Opening:           "Abriendo archivo remoto…",
			Loaded:            "Archivo remoto abierto.",
			Saving:            "Guardando y verificando el archivo remoto…",
			Saved:             "Guardado y verificado.",
			Reloading:         "Recargando desde el servidor…",
			Reloaded:          "Recargado desde el servidor.",
			Conflict:          "El archivo del servidor cambió después de abrirlo. Tus cambios se conservaron; recarga antes de volver a guardar.",
			Unsupported:       "Selecciona un archivo de texto normal de hasta 4 MiB. Carpetas, enlaces, archivos binarios y archivos mayores no se editan directamente.",
			DiscardClose:      "Hay cambios sin guardar. Pulsa Cerrar otra vez para descartarlos.",
			DiscardReload:     "Recargar descartará los cambios sin guardar. Pulsa Recargar otra vez.",
			MixedNewlines:     "Este archivo usa finales de línea mezclados. Ghost FTP no lo editará para evitar cambios no deseados.",
			ConnectionChanged: "La conexión al servidor cambió. Vuelve a abrir el archivo antes de guardar.",
		},
		"tr": {
			Edit:              "Düzenle",
			Title:             "Uzak düzenleyici",
			Save:              "Kaydet",
			Reload:            "Yeniden yükle",
			Close:             "Kapat",
			Hint:              "Ctrl+S kaydet · Ctrl+R yeniden yükle · Esc kapat",
			Opening:           "Uzak dosya açılıyor…",
			Loaded:            "Uzak dosya açıldı.",
			Saving:            "Uzak dosya kaydediliyor ve doğrulanıyor…",
			Saved:             "Kaydedildi ve doğrulandı.",
			Reloading:         "Sunucudan yeniden yükleniyor…",
			Reloaded:          "Sunucudan yeniden yüklendi.",
			Conflict:          "Sunucudaki dosya açıldıktan sonra değişti. Düzenlemeleriniz korundu; yeniden kaydetmeden önce dosyayı yenileyin.",
			Unsupported:       "4 MiB'a kadar tek bir normal metin dosyası seçin. Klasörler, bağlantılar, ikili ve daha büyük dosyalar yerinde düzenlenmez.",
			DiscardClose:      "Kaydedilmemiş değişiklikler var. Atmak için Kapat'a yeniden tıklayın.",
			DiscardReload:     "Yeniden yükleme kaydedilmemiş değişiklikleri atar. Devam etmek için yeniden tıklayın.",
			MixedNewlines:     "Bu dosyada karışık satır sonları var. Ghost FTP ilgisiz satırları değiştirmemek için düzenlemeyi reddeder.",
			ConnectionChanged: "Sunucu bağlantısı değişti. Kaydetmeden önce dosyayı yeniden açın.",
		},
		"el": {
			Edit:              "Επεξεργασία",
			Title:             "Απομακρυσμένος επεξεργαστής",
			Save:              "Αποθήκευση",
			Reload:            "Επαναφόρτωση",
			Close:             "Κλείσιμο",
			Hint:              "Ctrl+S αποθήκευση · Ctrl+R επαναφόρτωση · Esc κλείσιμο",
			Opening:           "Άνοιγμα απομακρυσμένου αρχείου…",
			Loaded:            "Το απομακρυσμένο αρχείο άνοιξε.",
			Saving:            "Αποθήκευση και επαλήθευση…",
			Saved:             "Αποθηκεύτηκε και επαληθεύτηκε.",
			Reloading:         "Επαναφόρτωση από τον διακομιστή…",
			Reloaded:          "Επαναφορτώθηκε από τον διακομιστή.",
			Conflict:          "Το αρχείο στον διακομιστή άλλαξε μετά το άνοιγμα. Οι αλλαγές σας διατηρήθηκαν· επαναφορτώστε πριν αποθηκεύσετε ξανά.",
			Unsupported:       "Επιλέξτε ένα κανονικό αρχείο κειμένου έως 4 MiB. Φάκελοι, σύνδεσμοι, δυαδικά και μεγαλύτερα αρχεία δεν επεξεργάζονται επιτόπου.",
			DiscardClose:      "Υπάρχουν μη αποθηκευμένες αλλαγές. Πατήστε ξανά Κλείσιμο για απόρριψη.",
			DiscardReload:     "Η επαναφόρτωση θα απορρίψει μη αποθηκευμένες αλλαγές. Πατήστε ξανά Επαναφόρτωση.",
			MixedNewlines:     "Το αρχείο χρησιμοποιεί μικτούς τερματισμούς γραμμών. Το Ghost FTP δεν θα το επεξεργαστεί για να αποφύγει άσχετες αλλαγές.",
			ConnectionChanged: "Η σύνδεση με τον διακομιστή άλλαξε. Ανοίξτε ξανά το αρχείο πριν την αποθήκευση.",
		},
		"pt": {
			Edit:              "Editar",
			Title:             "Editor remoto",
			Save:              "Guardar",
			Reload:            "Recarregar",
			Close:             "Fechar",
			Hint:              "Ctrl+S guardar · Ctrl+R recarregar · Esc fechar",
			Opening:           "A abrir ficheiro remoto…",
			Loaded:            "Ficheiro remoto aberto.",
			Saving:            "A guardar e verificar o ficheiro remoto…",
			Saved:             "Guardado e verificado.",
			Reloading:         "A recarregar do servidor…",
			Reloaded:          "Recarregado do servidor.",
			Conflict:          "O ficheiro no servidor mudou depois de ser aberto. As suas alterações foram mantidas; recarregue antes de voltar a guardar.",
			Unsupported:       "Selecione um ficheiro de texto normal até 4 MiB. Pastas, ligações, ficheiros binários e maiores não são editados diretamente.",
			DiscardClose:      "Existem alterações não guardadas. Clique novamente em Fechar para as descartar.",
			DiscardReload:     "Recarregar descartará alterações não guardadas. Clique novamente em Recarregar.",
			MixedNewlines:     "Este ficheiro usa finais de linha mistos. O Ghost FTP não o editará para evitar alterações não relacionadas.",
			ConnectionChanged: "A ligação ao servidor mudou. Reabra o ficheiro antes de guardar.",
		},
		"zh": {
			Edit:              "编辑",
			Title:             "远程编辑器",
			Save:              "保存",
			Reload:            "重新加载",
			Close:             "关闭",
			Hint:              "Ctrl+S 保存 · Ctrl+R 重新加载 · Esc 关闭",
			Opening:           "正在打开远程文件…",
			Loaded:            "远程文件已打开。",
			Saving:            "正在保存并验证远程文件…",
			Saved:             "已保存并验证。",
			Reloading:         "正在从服务器重新加载…",
			Reloaded:          "已从服务器重新加载。",
			Conflict:          "服务器文件在打开后已更改。您的编辑内容已保留；再次保存前请重新加载。",
			Unsupported:       "请选择一个不超过 4 MiB 的普通文本文件。文件夹、链接、二进制文件和更大的文件不会直接编辑。",
			DiscardClose:      "仍有未保存的更改。再次单击关闭以放弃这些更改。",
			DiscardReload:     "重新加载会放弃未保存的更改。再次单击重新加载以继续。",
			MixedNewlines:     "此文件使用混合换行符。为避免更改无关行，Ghost FTP 不会编辑它。",
			ConnectionChanged: "服务器连接已更改。保存前请重新打开文件。",
		},
		"ru": {
			Edit:              "Изменить",
			Title:             "Удалённый редактор",
			Save:              "Сохранить",
			Reload:            "Перезагрузить",
			Close:             "Закрыть",
			Hint:              "Ctrl+S сохранить · Ctrl+R перезагрузить · Esc закрыть",
			Opening:           "Открытие удалённого файла…",
			Loaded:            "Удалённый файл открыт.",
			Saving:            "Сохранение и проверка удалённого файла…",
			Saved:             "Сохранено и проверено.",
			Reloading:         "Перезагрузка с сервера…",
			Reloaded:          "Перезагружено с сервера.",
			Conflict:          "Файл на сервере изменился после открытия. Ваши изменения сохранены в редакторе; перезагрузите файл перед повторным сохранением.",
			Unsupported:       "Выберите один обычный текстовый файл размером до 4 MiB. Папки, ссылки, двоичные и более крупные файлы напрямую не редактируются.",
			DiscardClose:      "Есть несохранённые изменения. Нажмите Закрыть ещё раз, чтобы их отбросить.",
			DiscardReload:     "Перезагрузка отбросит несохранённые изменения. Нажмите Перезагрузить ещё раз.",
			MixedNewlines:     "В файле смешаны типы окончаний строк. Ghost FTP не будет его редактировать, чтобы не менять посторонние строки.",
			ConnectionChanged: "Соединение с сервером изменилось. Откройте файл заново перед сохранением.",
		},
		"hi": {
			Edit:              "संपादित करें",
			Title:             "रिमोट संपादक",
			Save:              "सहेजें",
			Reload:            "फिर लोड करें",
			Close:             "बंद करें",
			Hint:              "Ctrl+S सहेजें · Ctrl+R फिर लोड करें · Esc बंद करें",
			Opening:           "रिमोट फ़ाइल खोली जा रही है…",
			Loaded:            "रिमोट फ़ाइल खुल गई।",
			Saving:            "रिमोट फ़ाइल सहेजी और जाँची जा रही है…",
			Saved:             "सहेजा और सत्यापित किया गया।",
			Reloading:         "सर्वर से फिर लोड किया जा रहा है…",
			Reloaded:          "सर्वर से फिर लोड किया गया।",
			Conflict:          "सर्वर फ़ाइल खुलने के बाद बदल गई। आपके बदलाव रखे गए हैं; दोबारा सहेजने से पहले फिर लोड करें।",
			Unsupported:       "4 MiB तक की एक सामान्य टेक्स्ट फ़ाइल चुनें। फ़ोल्डर, लिंक, बाइनरी और बड़ी फ़ाइलें सीधे संपादित नहीं की जातीं।",
			DiscardClose:      "कुछ बदलाव सहेजे नहीं गए हैं। उन्हें छोड़ने के लिए बंद करें पर फिर क्लिक करें।",
			DiscardReload:     "फिर लोड करने से बिना सहेजे बदलाव हटेंगे। जारी रखने के लिए फिर क्लिक करें।",
			MixedNewlines:     "इस फ़ाइल में मिश्रित लाइन एंडिंग हैं। असंबंधित पंक्तियाँ बदलने से बचने के लिए Ghost FTP इसे संपादित नहीं करेगा।",
			ConnectionChanged: "सर्वर कनेक्शन बदल गया है। सहेजने से पहले फ़ाइल फिर खोलें।",
		},
		"ja": {
			Edit:              "編集",
			Title:             "リモートエディター",
			Save:              "保存",
			Reload:            "再読み込み",
			Close:             "閉じる",
			Hint:              "Ctrl+S 保存 · Ctrl+R 再読み込み · Esc 閉じる",
			Opening:           "リモートファイルを開いています…",
			Loaded:            "リモートファイルを開きました。",
			Saving:            "リモートファイルを保存して検証しています…",
			Saved:             "保存して検証しました。",
			Reloading:         "サーバーから再読み込みしています…",
			Reloaded:          "サーバーから再読み込みしました。",
			Conflict:          "サーバー上のファイルは開いた後に変更されました。編集内容は保持されています。再度保存する前に再読み込みしてください。",
			Unsupported:       "4 MiB 以下の通常のテキストファイルを1つ選択してください。フォルダー、リンク、バイナリ、大きなファイルは直接編集しません。",
			DiscardClose:      "未保存の変更があります。破棄するにはもう一度［閉じる］をクリックしてください。",
			DiscardReload:     "再読み込みすると未保存の変更が破棄されます。続行するにはもう一度［再読み込み］をクリックしてください。",
			MixedNewlines:     "このファイルには複数種類の改行コードが混在しています。無関係な行を変更しないため Ghost FTP は編集を拒否します。",
			ConnectionChanged: "サーバー接続が変更されました。保存する前にファイルを開き直してください。",
		},
	}
	if value, ok := words[language]; ok {
		return value
	}
	return words["en"]
}
